# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yanke\Documents\Python\DDOOT\ddoot.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 40, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 40, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 40, 101, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 100, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 130, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(260, 100, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(260, 130, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(410, 100, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(410, 130, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(250, 200, 91, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(250, 240, 91, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 70, 47, 13))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 70, 47, 13))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 70, 47, 13))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        self.pushButton_3.pressed.connect(MainWindow.enableDeliveryOptimization) # type: ignore
        self.pushButton_4.pressed.connect(MainWindow.disableDeliveryOptimization) # type: ignore
        self.pushButton_5.pressed.connect(MainWindow.enableWaasMedicService) # type: ignore
        self.pushButton_6.pressed.connect(MainWindow.disableWaasMedicService) # type: ignore
        self.pushButton_7.pressed.connect(MainWindow.enableUsoSvc) # type: ignore
        self.pushButton_8.pressed.connect(MainWindow.disableUsoSvc) # type: ignore
        self.pushButton_9.pressed.connect(MainWindow.enableAll) # type: ignore
        self.pushButton_10.pressed.connect(MainWindow.disableAll) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DDOOT"))
        self.label_2.setText(_translate("MainWindow", "Delivery Optimization"))
        self.label_3.setText(_translate("MainWindow", "Windows Medic Service"))
        self.label_4.setText(_translate("MainWindow", "Update Orchestator"))
        self.pushButton_3.setText(_translate("MainWindow", "Enable"))
        self.pushButton_4.setText(_translate("MainWindow", "Disable"))
        self.pushButton_5.setText(_translate("MainWindow", "Enable"))
        self.pushButton_6.setText(_translate("MainWindow", "Disable"))
        self.pushButton_7.setText(_translate("MainWindow", "Enable"))
        self.pushButton_8.setText(_translate("MainWindow", "Disable"))
        self.pushButton_9.setText(_translate("MainWindow", "Enable All"))
        self.pushButton_10.setText(_translate("MainWindow", "Disable All"))
        self.label.setText(_translate("MainWindow", f"{MainWindow.status2}"))
        self.label_5.setText(_translate("MainWindow", f"{MainWindow.status3}"))
        self.label_6.setText(_translate("MainWindow", f"{MainWindow.status3}"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
